# Generated by Django 4.1.7 on 2023-08-15 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
