# Generated by Django 4.1.7 on 2023-08-17 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='details',
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.CharField(default='1kg', max_length=20),
        ),
    ]
