# Generated by Django 4.1.7 on 2023-08-17 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_product_details_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.FloatField(default=None, max_length=10),
        ),
    ]
