# Generated by Django 4.1.7 on 2023-08-22 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_category_cat_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_draft',
            new_name='in_stock',
        ),
    ]
